### ISSUE TITLE
nicer way of defining function parameters

### ISSUE THREAD

**Issue by rbrick** [phase/lang-kotlin-antlr-compiler#3]
When defining function parameters would you be able to do something along the lines of
```rust
add(a, b : Int) 
    a + b
```
where `a` and `b` are both inferred as type `Int`

**Comment by phase** [comment]
This should be simple to do if we traverse the formals backwards and assign any empty types to the previous formal's type.

```
previousType = null
for formal in formals.reverse()
  if formal.type != null
    previousType = formal.type
  else
    formal.type = previousType
```
